"""empty message

Revision ID: a9e94b75e80a
Revises: 9a8e1f2b0fdb
Create Date: 2022-07-11 08:33:04.488850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e94b75e80a'
down_revision = '9a8e1f2b0fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('web_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'web_link')
    # ### end Alembic commands ###
